pipeline:
  build:
    image: astronomerio/ap-build:0.1.1
    commands:
      - docker build -t astronomerinc/ap-orbit-ui:dev .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: push

  test:
    image: astronomerinc/ap-orbit-ui:dev
    commands:
      - cd /srv/orbit-ui
      - npm test
    when:
      event: push

  push:
    image: astronomerio/ap-build:0.1.1
    commands:
      - docker login -u $${DOCKER_USERNAME} -p $${DOCKER_PASSWORD}
      - docker push astronomerinc/ap-orbit-ui:dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets: [ docker_username, docker_password ]
    when:
      event: push
      branch: [ master ]

  # Trigger build of production images from master
  trigger:
    image: plugins/downstream
    server: http://drone.astronomer.io
    fork: true
    secrets: [ downstream_token ]
    repositories:
      - astronomer/astronomer
    when:
      event: push
      branch: master

  notify:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: platform
    when:
      status: [ failure ]
