export default {
  AIRFLOW_HOME: '',
  C_FORCE_ROOT: '',
  CONTAINER_NAME: '',
  DAGS_FOLDER: '',
  GCP_PROJECT: '',
  GCS_BUCKET: '',
  GKE_CLUSTER_NAME: '',
  SQL_DATABASE: '',
  SQL_INSTANCE: '',
  SQL_PASSWORD: '',
  SQL_PROJECT: '',
  SQL_REGION: '',
  SQL_USER: '',
}
