version: 2.1
jobs:
  build:
    executor: docker-executor
    steps:
      - docker-build:
          image_name: ap-orbit-ui
          dockerfile: Dockerfile.prod
  scan:
    executor: clair-scanner/default
    steps:
      - clair-scan:
          image_name: ap-orbit-ui
  publish-dev:
    executor: docker-executor
    steps:
      - push:
          comma_separated_tags: "dev,edge,$CIRCLE_SHA1"
          image_name: ap-orbit-ui
  publish-prod:
    executor: docker-executor
    steps:
      - push:
          comma_separated_tags: "master,latest"
          image_name: ap-orbit-ui
workflows:
  version: 2.1
  build-images:
    jobs:
      - build
      - scan:
          requires:
            - build
      - publish-dev:
          requires:
            - scan
      - publish-prod:
          requires:
            - scan
          filters:
            branches:
              only: master
orbs:
  clair-scanner: ovotech/clair-scanner@1.6.0
executors:
  docker-executor:
    environment:
      GIT_ORG: astronomerinc
    docker:
      - image: circleci/buildpack-deps:stretch
commands:
  docker-build:
    description: "Build a Docker image"
    parameters:
      dockerfile:
        type: string
        default: Dockerfile
      path:
        type: string
        default: "."
      image_name:
        type: string
        default: $CIRCLE_PROJECT_REPONAME
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the Docker image
          command: |
            set -xe
            image_name="<< parameters.image_name >>"
            docker build -t $image_name --file << parameters.path>>/<< parameters.dockerfile >> --build-arg BUILD_NUMBER=${CIRCLE_BUILD_NUM} << parameters.path >>
            docker save -o << parameters.image_name >>.tar $image_name
      - persist_to_workspace:
          root: .
          paths:
            - './*.tar'
  clair-scan:
    description: "Vulnerability scan a Docker image"
    parameters:
      image_name:
        type: string
        default: $CIRCLE_PROJECT_REPONAME
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Move tarball to directory for scan
          command: mkdir /tmp/tarballs && mv /tmp/workspace/<< parameters.image_name >>.tar /tmp/tarballs/
      - clair-scanner/scan:
          docker_tar_dir: /tmp/tarballs
  push:
    description: "Push a Docker image to DockerHub"
    parameters:
      comma_separated_tags:
        type: string
        default: latest
      organization:
        type: string
        default: $GIT_ORG
      image_name:
        type: string
        default: $CIRCLE_PROJECT_REPONAME
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/<< parameters.image_name >>.tar
      - run:
          name: Login to DockerHub
          command: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
      - run:
          name: Push Docker image(s)
          command: |
            set -e
            for tag in $(echo "<< parameters.comma_separated_tags >>" | sed "s/,/ /g");
            do
              set -x
              docker tag << parameters.image_name >> << parameters.organization >>/<< parameters.image_name >>:${tag}
              docker push << parameters.organization >>/<< parameters.image_name >>:${tag}
              set +x
            done
